FROM wazuh/wazuh-indexer:4.14.5

# Copy SSL certificates
COPY config/wazuh_indexer_ssl_certs/root-ca.pem /usr/share/wazuh-indexer/config/certs/root-ca.pem
COPY config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem /usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
COPY config/wazuh_indexer_ssl_certs/wazuh.indexer.pem /usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
COPY config/wazuh_indexer_ssl_certs/admin.pem /usr/share/wazuh-indexer/config/certs/admin.pem
COPY config/wazuh_indexer_ssl_certs/admin-key.pem /usr/share/wazuh-indexer/config/certs/admin-key.pem

# Copy indexer configuration
COPY config/wazuh_indexer/wazuh.indexer.yml /usr/share/wazuh-indexer/config/opensearch.yml
COPY config/wazuh_indexer/internal_users.yml /usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml

USER root
RUN chmod 600 /usr/share/wazuh-indexer/config/certs/*.pem \
              /usr/share/wazuh-indexer/config/certs/*.key 2>/dev/null || true
